#index:
#    path: /
#    controller: App\Controller\DefaultController::index

web_user_controllers:
  resource: '../src/User/Presentation/Controller/'
  type: annotation

web_appointment_controllers:
  resource: '../src/Appointment/Presentation/Controller/'
  type: annotation